sonar.organization=epnaj
sonar.projectKey=epnaj-projektowanie-obiektowe

sonar.sources=zadanie3/src,zadanie4,zadanie5/client/src,zadanie5/server

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.*,**/*.min.js

sonar.sourceEncoding=UTF-8
